#raise Exception
#print "I raised an exception!"

try:
<<<<<<< HEAD:Day3/Class3_.py
 	print b
=======
    print b
>>>>>>> carlson9/master:Day3/Class3.py
except NameError:
	print "oops name error"	
except:
	print "opps"
finally:
	print "Yes! I did it!"
	
	
for i in range(1,10):
	if i==5:
		print "I found five!"
		break #continue
		print "Here is five!"
	else:
		print i
	
		
else:
	print "I went through all iterations!"

